name: GCdynamics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - scikit-learn
  - numba
  - jupyterlab
  - matplotlib
  - pandas
  - jupyter
  - numpy
  - ipykernel
  - h5py
  - tqdm
  - seaborn
  - scipy
  - pip
  - pip:
    - typed-argument-parser
